### ISSUE TITLE
[Feature Request] Allow customization of TLS server name (SNI) in ServersTransport

### ISSUE THREAD

**Issue by 4nx** [fosrl/pangolin#452]
**Background:**
When using Pangolin in setups involving multiple reverse proxies (such as Traefik in a two-tier reverse proxy configuration), the server name used during the TLS handshake (SNI) to backend servers is currently not configurable and not set. As reported in [Issue #207](https://github.com/fosrl/pangolin/issues/207), this limitation causes TLS handshake failures because the backend reverse proxy does not receive the correct server name via SNI and thus cannot select the appropriate certificate.

**Proposed Enhancement:**
Implement an option within Pangolin's configuration to explicitly specify the TLS server name used during the connection establishment with backend services (ServersTransport). This would allow users to define a custom SNI value, ensuring proper TLS handshakes in scenarios involving multiple reverse proxies.

**Benefits:**
* Resolves TLS handshake failures by ensuring correct SNI is passed to backend services.
* Enables smoother integration with multi-layer reverse proxy setups.
* Provides greater flexibility and robustness for advanced network configurations.

**Related Issues:**
Directly addresses problems discussed in [Issue #207](https://github.com/fosrl/pangolin/issues/207), specifically regarding TLS handshake errors caused by incorrect or missing SNI information.

**Comment by oschwartz10612** [comment]
Thanks for the feature request! I will leave this open instead of moving it to a discussion because I think it is a good first thing for someone to solve or we will do it soon!

**Comment by asychev** [comment]
+1
I have split DNS setup and internal Reverse Proxy (Nginx Proxy Manager) requires SNI to work properly.

**Comment by franzfopa** [comment]
SNI and ldap/oidc (to a lesser extent) are the two features that makes this project something I become a "full supporter" for - love the development speed and simplicity.

**Comment by mschirrmeister** [comment]
Is https://github.com/fosrl/pangolin/pull/501 going to address this?

**Comment by miloschwartz** [comment]
@mschirrmeister I believe so

**Comment by mschirrmeister** [comment]
Technically I am sure it is addressing it. I guess my mind was more at the process, if this one here is just kept open until #501 is included in a GA release.

**Comment by mschirrmeister** [comment]
Just tested `1.3.0` and all looks good. Thank you very much.

**Comment by 4nx** [comment]
I cannot confirm that the setting in the Advanced TLS Settings is working as expected. I observed that the request reaches the second reverse proxy with the host header still set to the service name that Pangolin is using externally.

For example, if Pangolin exposes a service as unifi.example.com, but the internal service expects requests for unifi.internal.com, then even after setting unifi.internal.com in the Advanced TLS Settings, the request is still forwarded with the host header unifi.example.com.

This causes routing issues on the downstream proxy, as it doesn't match the expected host.

**Comment by 4nx** [comment]
@mschirrmeister can you confirm that the setting on your setup is working as expected? Did you have a look on the requests which pangolin is doing?

@miloschwartz maybe you could reopen the feature request as it seems not working.

**Comment by achtnullzwei** [comment]
I can confirm this is indeed not working as expected. Checked 1.3.0 and 1.3.1 (looking directly at the database)

Current behaviour:
1) Set TLS Server Name
2) Setting gets reflected properly in DB
3) Set Host Header
4) Host Header gets set, but TLS Server Name setting gets removed.
5) Set TLS Server Name (again).
6) Host Header Setting gets removed.
...

Settings should not be coupled this way.

@miloschwartz  @4nx

**Comment by miloschwartz** [comment]
Thanks everyone this is bug I will get fixed here shortly. Hope to have a new release out soon.

**Comment by mschirrmeister** [comment]
@4nx I did not run into this, because my internal services have the same name as on the external side.

Despite the still existing bug that @achtnullzwei described and based on what you described, you need to set your internal name in 2 places, not only the `TLS Server Name (SNI)`. 
The `Custom Host Header` is the field for all http level stuff and to find the correct _virtual host_.

The TLS stuff is **only** important during the TLS handshake.

**Comment by 4nx** [comment]
@mschirrmeister ok with the same name it would work sure. 

My problem is indeed first of all the SNI request because this fails first. I am not quite sure if you really need the custom host header as well but indeed it should be possible to configure both not only one at a time. 

@miloschwartz thx for adressing this as a bug!
